/** Suggestions for the city field. Free text is still allowed. Hebrew names, used with the Hebrew locale. */
export const ISRAELI_CITY_SUGGESTIONS = [
  'ירושלים',
  'תל אביב-יפו',
  'חיפה',
  'ראשון לציון',
  'פתח תקווה',
  'אשדוד',
  'נתניה',
  'באר שבע',
  'בני ברק',
  'חולון',
  'רמת גן',
  'אשקלון',
  'רחובות',
  'בת ים',
  'בית שמש',
  'כפר סבא',
  'הרצליה',
  'חדרה',
  'מודיעין-מכבים-רעות',
  'רעננה',
  'לוד',
  'רמלה',
  'נצרת',
  'עפולה',
  'אילת',
] as const;
